### ISSUE TITLE
More addons

### ISSUE THREAD

**Issue by quick007** [akd-io/create-next-stack#123]
Can you please add these addons:

- tailwindcss
- nightwindcss 
- typescript
- no css toggle
- heroicons/react

**Comment by akd-io** [comment]
Hey @quick007, thanks for showing interest!

To address your ideas one by one:
- Tailwind: I'm glad to announce that [Tailwind support is here](https://www.create-next-stack.com/).
- Nightwind: I've create a new issue to track support for Nightwind. #134
- Typescript: TS is currently required, and you can't opt out. Plain JavaScript is tracked in #133.
- No CSS toggle: Here, do you mean choosing no styling option? The CSS Modules option actually doesn't do anything, as it is supported by Next.js out of the box. But maybe I should add a "None" option, just so people don't think they are getting served something they don't need. Would you agree?
- heroicons/react: This will be supported as part of #132.

**Comment by akd-io** [comment]
I decided to add the "None" option. Tracked here https://github.com/akd-io/create-next-stack-website/issues/44

**Comment by quick007** [comment]
Great, thanks!
