### ISSUE TITLE
Add support for 3rd party component libraries

### ISSUE THREAD

**Issue by akd-io** [akd-io/create-next-stack#35]
Component libraries to support:
- [x] [Material UI](https://material-ui.com/) (#111)
- [x] Mantine (#202 & #210)
- [ ] #211
- [ ] #212
- more?

**Comment by leerob** [comment]
https://radix-ui.com/

**Comment by jamesinaxx** [comment]
I have forked and am working on adding [Material UI](https://material-ui.com/), as of now it simply installs it with the rest of the dependencies if enabled, but I can add more functionality if desired. If you could list what would be required for it to be ready that would be amazing :)

**Comment by akd-io** [comment]
> I have forked and am working on adding [Material UI](https://material-ui.com/), as of now it simply installs it with the rest of the dependencies if enabled, but I can add more functionality if desired. If you could list what would be required for it to be ready that would be amazing :) 

Hey @jamesinaxx, sounds great!

The Next.js + Material UI example (https://github.com/vercel/next.js/tree/canary/examples/with-material-ui) refers to https://github.com/mui-org/material-ui/tree/master/examples/nextjs

So you can check that out to get an idea about what should be added to the generation of _app.ts and _document.ts.

Unfortunately I haven't refactored the code base yet, so you'll have to dig around a bit to find out how to add content to those two files.

**Comment by akd-io** [comment]
Remaining component libraries moved to individual issues
