### ISSUE TITLE
Add opt-out option

### ISSUE THREAD

**Issue by mpagels** [akd-io/create-next-stack#74]
Hey, what if I want to spin up a project, but don't need a form library?
For whatever reason. I thought, maybe an `opt-out` here would be a good idea. 

What do you think?

**Comment by akd-io** [comment]
You shouldn't be forced to add a form library! It's just checked by default for convenience.

Maybe that's not convenient, I'll have to check usage numbers at some point. The defaults should roughly cover the 80% use case.
